require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, '15.1'

target 'ritma_ed' do
  config = use_native_modules!

  # Disable New Architecture for better compatibility
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  require_relative '../node_modules/react-native-permissions/scripts/setup'
  setup_permissions([
    'Camera',
    'PhotoLibrary',
  ])

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  post_install do |installer|
    react_native_post_install(installer)
    
    # Set deployment target
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end